### ISSUE TITLE
Layout issue for front end GUI

### ISSUE THREAD

**Issue by tylerscheifley** [tylerscheifley/CSCN73030_PC_PayloadOps_Group2#12]
Since I have a smaller screen size the earth image is not side by side with the satellite image. Needs to be auto adujusted to accommodate smaller screens.  
<img width="547" alt="image" src="https://github.com/tylerscheifley/CSCN73030_PC_PayloadOps_Group2/assets/90644730/fb22ae27-01fc-41aa-9503-0cda935ccbde">

**Comment by BroCoRo** [comment]
Migrated to azure
