### ISSUE TITLE
Regression test fails for front-end

### ISSUE THREAD

**Issue by BroCoRo** [tylerscheifley/CSCN73030_PC_PayloadOps_Group2#2]
Some updates were made to add text descriptions in commit bd61701.

![image](https://github.com/tylerscheifley/CSCN73030_PC_PayloadOps_Group2/assets/85836332/bf421ffb-febf-41fc-86a9-7f2e7cd6035a)

**Comment by RyanCoding19** [comment]
Fixed these test mistakes in 0e4c837c48f0a246aa954034322ad5da059c861f git error by changed what text the tests were looking for
